---
- name: Download WordPress  
  get_url: 
    url: https://wordpress.org/latest.tar.gz 
    dest: /tmp/wordpress.tar.gz
    validate_certs: no
  become: yes

- name: Extract WordPress 
  unarchive: 
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes

- name: Moving WordPress configuration file
  template:
    src: wp-config.j2
    dest: /var/www/html/wordpress/wp-config.php

- name: Change file ownership, group and permissions
  file:
    path: /var/www/html/wordpress/
    state: directory
    recurse: yes
    group: www-data
    owner: www-data
    mode: '755'
  become: yes
  notify: restart nginx