vcenter_hostname:
vcenter_datacenter:
vcenter_cluster:
vcenter_datastore:
vcenter_folder:
vcenter_network:
ova_url: "http://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.ova"
ova_path: "./downloads/bionic-server-cloudimg-amd64.ova"